---
name: Workflow - Pull Request (on Close)

on:
  # pull_request:
  #   types:
  #     - closed
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
